name: Daily Scholarship Scraper
on:
  schedule:
    - cron: '0 0 * * *' # Runs every night at midnight
  workflow_dispatch: # Allows you to run it manually
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
        uses: os-actions/setup-python@v2
      - name: Install tools
        run: pip install -r requirements.txt
      - name: Run Robot
        env:
          GEMINI_API_KEY: ${{ secrets.GEMINI_API_KEY }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_KEY: ${{ secrets.SUPABASE_KEY }}
        run: python robot.py
